CREATE TABLE User (
  userId STRING(36) NOT NULL,
  name STRING(MAX) NOT NULL,
) PRIMARY KEY(userId);
CREATE TABLE UserItem (
  userId STRING(36) NOT NULL,
  userItemId STRING(36) NOT NULL,
  count INT64 NOT NULL,
) PRIMARY KEY(userId, userItemId), INTERLEAVE IN PARENT User ON DELETE CASCADE;